#!/bin/sh
#########################
# wm independent hotkeys
# @ => trigger on release
# 

#########################
# Command starts
#~Control_L
#	:
#~Alt_L
#	:
#~Super_L
#	:

#####################
# CTRL based commands

# language
#super + F1 
XF86Calculator
    sh -c 'if setxkbmap -query | grep -q "layout:\s*se"; then setxkbmap us; else setxkbmap se; fi'

# Move node
ctrl + alt + {h,j,k,l}
	bspc node -s {west.local, south, north, east.local}

# Toggle terminal
ctrl + super + @space
	~/.config/bspwm/dropterm.sh "dropdown"

# Toggle emacs
alt + @space
	~/.config/bspwm/dropterm.sh "Doom Emacs"


####################
# ALT based commands

# Focus node
alt + {h,j,k,l}
	bspc node -f {west,south,north,east}

# Rotate nodes
alt + {_,shift + } grave
	bspc node -f @parent && bspc node -R {-90,90} && bspc node -f @first

# Set state
alt + {t,r,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# Set flags
alt + {1,2,3,4}
	~/.config/bspwm/set_nodeflag.sh {sticky,private,locked,marked}

# Focus next/previous node
alt + {_,shift + }Tab
	bspc node -f {next,prev}.local.!hidden.window

## Close 
alt + w
	bspc node -c


######################
# SUPER based commands

# Focus desktop
super + {1-9,0}
	bspc desktop -f '^{1-9,10}'

# Focus next/prev desktop
super + {h,l}
	bspc desktop -f {prev,next}

# Bring node to next/prev desktop
super + ctrl + {h,l}
	bspc node -d {prev.local,next.local} --focus 

# Send to desktop
super + shift + {1-9,0}
	bspc node -d '^{1-9,10}'

## terminal
super + Return
	alacritty

## rofi
super + @space
	rofi -show drun

super + @b
	brave

# toggle between the tiled and monocle layout
super + f
	bspc desktop -l next

# sxhkd reload
super + Escape
	pkill -USR1 -x sxhkd

# reload bspwmrc
super + shift + r
	bspc {wm -r} && pkill -USR1 -x sxhkd

# quit/restart bspwm
super + shift + q
	bspc {quit,wm -r}


###############
# Screenshot

# screenshot
Print
    scrot 'screenshot_%Y%m%d_%H%M%S.png' -e 'mkdir -p ~/screenshots && mv $f ~/screenshots && xclip -selection clipboard -t image/png -i ~/screenshots/`ls -1 -t ~/screenshots | head -1`'

# screenshot region
shift + Print
    scrot -s 'screenshot_%Y%m%d_%H%M%S.png' -e 'mkdir -p ~/screenshots && mv $f ~/screenshots && xclip -selection clipboard -t image/png -i ~/screenshots/`ls -1 -t ~/screenshots | head -1`'



#XF86AudioPlay 
#	
#XF86AudioNext 
#
#XF86AudioPrev 

# Add keybindings for volume and lightness
#
XF86AudioRaiseVolume 
	pactl set-sink-volume @DEFAULT_SINK@ +10% 
XF86AudioLowerVolume 
	pactl set-sink-volume @DEFAULT_SINK@ -10%
XF86AudioMute 
	pactl set-sink-mute @DEFAULT_SINK@ toggle 
#XF86AudioMicMute 
#	pactl set-source-mute @DEFAULT_SOURCE@ toggle 
#
#XF86MonBrightnessUp 
#        light -A 5
#XF86MonBrightnessDown 
#        light -U 5
#
#
#XF86Calculator 
#	speedcrunch
